# Site settings
author: Harleigh Abel
title: From Madness to Mastery
header-img: img/home-bg.png
email: harleighabel@gmail.com
copyright_name: Harleigh Abel
description: > # this means to ignore newlines until "baseurl:"
  A Developers Journey 
baseurl: "https://dev.to/atxrenegade" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  atxrenegade

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
